### ISSUE TITLE
Annotations at maximum zoom level are not visible

### ISSUE THREAD

**Issue by riccardoch** [ribl/FBAnnotationClusteringSwift#1]
If I have annotations at the same map coordinates and I expand the map at maximum zoom level, those annotations remain into a FBAnnotationCluster and are not visible as single annotations.
Is there a way to allow displaying single annotations at maximum zoom level? @chenr2

**Comment by chenr2** [comment]
There's a discussion of this on the original repo:
https://github.com/infinum/FBAnnotationClustering/issues/11
They say that pins on identical coordinates would be superimposed anyway, so the approach is to deal with them on the callout. 

What do you think? @riccardoch

**Comment by riccardoch** [comment]
Probably is the best solution, because it difficult to interact with pins with the same coordinates
Thanks for the fast response @chenr2
