### ISSUE TITLE
Fatal error: FBZoomScaleToZoomLevel

### ISSUE THREAD

**Issue by AdAvAn** [ribl/FBAnnotationClusteringSwift#11]
Hi, I found the problem:

I'm trying to map the 3600 points.

In proetsesse job application takes off on error

Functions "FBZoomScaleToZoomLevel"
The text of the error: "fatal error: floating point value can not be converted to Int because it is either infinite or Nan"
Line 169
File "FBClusteringManager.swift".

![err](https://cloud.githubusercontent.com/assets/13752342/12269140/9482e69a-b958-11e5-9bc0-5cbe7c1462c9.jpg)

I noticed that this error is presented not every time, sometimes the point of time will be displayed correctly.

What could be the problem?
Thank you

**Comment by chenr2** [comment]
So, the original repo reported this issue also, and they suggested not inputting certain values into `FBZoomScaleToZoomeLevel(_:)` such as zero.
https://github.com/infinum/FBAnnotationClustering/issues/21

I just pushed up a commit that guards against infinite values of `floorLog2ScaleFloat`.
https://github.com/ribl/FBAnnotationClusteringSwift/commit/14a7facbbee6785606509a65925a093c2c467fd3

Can you test whether this fixes the crash in your project?

**Comment by AdAvAn** [comment]
I have made these changes to the file "FB Clustering Manager.svift."

I got this error in another line # 64:  "fatal error: floating point value can not be converted to Int because it is either infinite or NaN".

![err2](https://cloud.githubusercontent.com/assets/13752342/12288743/8c64b4f2-b9df-11e5-8c50-c064d125d92b.jpg)

**Comment by chenr2** [comment]
Within your own code, you are calling this method:

``` swift
clusteringManager.clusteredAnnotationsWithinMapRect(self.mapView.visibleMapRect, withZoomScale:scale)
```

According to the debugger, `zoomScale` is infinity.  How are you calculating `scale` -- is it possible that your app code is encountering a divide by zero edge case?

**Comment by AdAvAn** [comment]
Yes you are right, app gets a zero in the way of calculating.
"scale" is calculated as follows: 

```
 let mapBoundsWidth = Double(self.mapKitView.bounds.size.width)
 let mapRectWidth:Double = self.mapKitView.visibleMapRect.size.width
 let scale:Double = mapBoundsWidth / mapRectWidth
```

The result of the calculations to the error:

```
mapBoundsWidth = 600.0
mapRectWidth = 134200854.601533
scale = 4.47091042587999e-06
mapBoundsWidth = 600.0
mapRectWidth = 134200854.601533
scale = 4.47091042587999e-06
mapBoundsWidth = 600.0
mapRectWidth = 0.0
scale = inf
fatal error: floating point value can not be converted to Int because it is either infinite or NaN
```

**Comment by chenr2** [comment]
I just added a commit https://github.com/ribl/FBAnnotationClusteringSwift/commit/09f5b41d77f59a9e4f4250728ae09d4eef600b9f that guards against an infinite `zoomScale`, in case the app code resizes the map to a zero width. The `guard` statement just returns an empty array of annotations, since the map is probably shrunk and hidden anyway.  Can you give this a try?

**Comment by AdAvAn** [comment]
Yes, I can confirm that the application is stable.
Thanks for the help.
