### ISSUE TITLE
Cocoa pods required 9.0

### ISSUE THREAD

**Issue by lucasromanomr** [ribl/FBAnnotationClusteringSwift#14]
The library is set to ios 9. Now she works only for ios9 on? this is due to an error?

**Comment by chenr2** [comment]
@freemiumdev The `FBAnnotationClusteringSwift.podspec` is actually pointing to your freemiumdev/FBAnnotationClusteringSwift fork. Can you set your `s.platform` version to accommodate @lucasromanomr?  Thanks!

**Comment by lucasromanomr** [comment]
My project has to meet the versions from iOS8, then this set of pods to 8.0

So I was trying to give install pod seemed to me the error saying that the pod version did not work on my project, would work only if my project was to ios 9 onwards.

**Comment by freemiumdev** [comment]
@chenr2 the code work on ios 8?

**Comment by chenr2** [comment]
@freemiumdev Yes, the code should work on iOS 8. The only iOS 9 code is the `pinTintColor` in the sample project.
