### ISSUE TITLE
Clusters Refresh rate

### ISSUE THREAD

**Issue by uknowmeright** [ribl/FBAnnotationClusteringSwift#16]
Whenever I zoom in or out the Clusters recalculate where they should be but there is major flashing going on while they do this. All the annotations flash on and off the screen. This would be a really bad experience for the users. Do you have any suggestions on how to fix this? Thanks!

**Comment by chenr2** [comment]
@uknowmeright Yeah, it would be awesome if the zoom transitions were animated, much like a `collectionView.reloadSections()`. Maybe have a larger cluster, say of size 65 go through mitosis and turn into two smaller clusters of 29 and 36. This does sound like a heavy lift, so I probably won't get to this anytime soon. (If this is urgent, you can contact ThornTech and we can work something out.)

One workaround might be to animate the `addAnnotations` and `removeAnnotations` so they don't all happen at once. Zillow does something like this, so it looks like red dots appear on the map like the measles. 

![zillow](https://cloud.githubusercontent.com/assets/10889121/13434352/7e53e54c-dfa3-11e5-956a-2a706c5ae546.gif)
