### ISSUE TITLE
Not updated for Swift 2

### ISSUE THREAD

**Issue by MKelman** [ribl/FBAnnotationClusteringSwift#2]
Is there a possibility we could transition this to Swift 2?

**Comment by chenr2** [comment]
We may update to Swift 2 in the near future, but you are welcome to submit a pull request.  Thanks for adding this issue!

**Comment by arashparnia** [comment]
I have upgraded this to swift 2 and its working. i don't know how this works.. but i could post the changes.

**Comment by MKelman** [comment]
Was there any issues or did it convert perfectly with apple's swift 2 converter?

**Comment by arashparnia** [comment]
my code needed a lot of change after using the convertor, but as far as i remember i changed this for FBClusteringMaganer/displayAnnotations function 
            mapView.addAnnotations(toAdd.allObjects as! [MKAnnotation])
            mapView.removeAnnotations(toRemove.allObjects as! [MKAnnotation])

added as! [MKAnnotation]

**Comment by nicolasFernandez** [comment]
I'm having
 Type of title has different optionality than required by protocol 'MKAnnotation' in FBAnnotation class

class FBAnnotation : NSObject {

```
var coordinate = CLLocationCoordinate2D(latitude: 39.208407, longitude: -76.799555)
var title = ""
```

}

Has anyone solved this? 

I solved this by changing to 

var title:String? = ""

**Comment by chenr2** [comment]
@nicolasFernandez Thanks for documenting the error and solution to the `MKAnnotation` protocol change.

Also, Master has been updated for Swift 2, via pull request.  The Swift 1.2 code is on a branch "Xcode6".
