### ISSUE TITLE
Select annotation only work for cluster

### ISSUE THREAD

**Issue by Alex293** [ribl/FBAnnotationClusteringSwift#35]
Hi, 

I have an issue with select detection. It work with clusters and phone location pin but not with simple pins (added in cluster manager but not in cluster). I think I made a mistake, so I tested against you exemple and it fail too : 

**func mapView(mapView: MKMapView, didSelectAnnotationView view: MKAnnotationView)
{
        print("Selected annotation")
}**

_-> log only for user location pin and clusters_

and/or : 

func mapView(mapView: MKMapView, viewForAnnotation annotation: MKAnnotation) -> MKAnnotationView?
{
    if annotation.isKindOfClass(FBAnnotationCluster)
    {
        reuseId = "Cluster"
        var clusterView = mapView.dequeueReusableAnnotationViewWithIdentifier(reuseId)
        clusterView = FBAnnotationClusterView(annotation: annotation, reuseIdentifier: reuseId, options: nil)
        **clusterView?.canShowCallout = true**
        return clusterView  
     }
     else
     {
         reuseId = "Pin"
         var pinView = mapView.dequeueReusableAnnotationViewWithIdentifier(reuseId) as? MKPinAnnotationView
         pinView = MKPinAnnotationView(annotation: annotation, reuseIdentifier: reuseId)
         **pinView!.pinTintColor = UIColor.blueColor()
         pinView!.canShowCallout = true**
         return pinView
     }
}

_-> show callout only for cluster and user location pin but pins are blue so they've been affected by the code_

**Comment by 3viewgroup** [comment]
I have the same problem like you

**Comment by jassadakorn** [comment]
Just remove  `reuseId = "Pin"
var pinView = mapView.dequeueReusableAnnotationViewWithIdentifier(reuseId) as? MKPinAnnotationView
pinView = MKPinAnnotationView(annotation: annotation, reuseIdentifier: reuseId)` after else

**Comment by edumucelli** [comment]
Same here.

**Comment by nuthanbanad** [comment]
How to receive taps on cluster and get all annotations in that cluster to display in a list.
