### ISSUE TITLE
Clear Tree

### ISSUE THREAD

**Issue by croossin** [ribl/FBAnnotationClusteringSwift#6]
I have found that if I try to repopulate my map, it doesnt erase the pins that are already there.  Is there a clear() function or something of the sort that just wipes the map and starts over?

**Comment by chenr2** [comment]
There isn't a method that clears and resets the map. But you could probably just set the annotations:

``` swift
clusteringManager.setAnnotations([])
```

And then within the `ViewController`, re-render the current map region:

``` swift
let mapBoundsWidth = Double(self.mapView.bounds.size.width)
let mapRectWidth:Double = self.mapView.visibleMapRect.size.width
let scale:Double = mapBoundsWidth / mapRectWidth
let annotationArray = self.clusteringManager.clusteredAnnotationsWithinMapRect(self.mapView.visibleMapRect, withZoomScale:scale)
self.clusteringManager.displayAnnotations(annotationArray, onMapView:self.mapView)        
```
