### ISSUE TITLE
How do I get all annotations from a cluster ? Like if there is a cluster of 20 annotations, I want to get that data of 20 annotations.

### ISSUE THREAD

**Issue by ruchinsinghal** [ribl/FBAnnotationClusteringSwift#61]

**Comment by yannbu** [comment]
Hi, 

You closed the issue, did you found a solution ?

I would be interested to know how you did if this is the case.

Thanks

**Comment by mvorisis** [comment]
@Yungbubu write some details (or an example) of what you want to do so I can help you if I can
