### ISSUE TITLE
ContiguousArrayStorage memory leak

### ISSUE THREAD

**Issue by basuru13** [ribl/FBAnnotationClusteringSwift#65]
Hi,

I was testing the Example and found a leak just by zooming in and out. 

![screen shot 2017-01-26 at 3 38 08 pm](https://cloud.githubusercontent.com/assets/22106877/22350942/b5d84798-e3e3-11e6-9540-72a7fff27d8e.png)
![screen shot 2017-01-26 at 3 38 38 pm](https://cloud.githubusercontent.com/assets/22106877/22351030/2922e578-e3e4-11e6-9ba6-ca11a90b6a1d.png)

Any ideas how to get rid of the memory leak?

**Comment by bryan1anderson** [comment]
@basuru13 Did you close this because you figured it out?
