### ISSUE TITLE
how to use this library into objective c 

### ISSUE THREAD

**Issue by madBureaToT** [ribl/FBAnnotationClusteringSwift#75]
Hi there,
I want to use this library into objective C.
But i can't able  to access some methods of clustering manager.

As we can use file in objective that having super class with NSObject then we can add @objc .
Most of swift class is not of NSObject class.

So How to use that file into objective c

**Comment by antoinelamy** [comment]
You cannot use this library using Objective-C, it use advanced swift features that are not compatible in objc such as enum associated values. I suggest you use the original project witch is written in Objective-C.

https://github.com/infinum/FBAnnotationClustering
